### ISSUE TITLE
Can I use any other script from context menu ?

### ISSUE THREAD

**Issue by khurshid-alam** [kotleni/FinderPlus-macOS#1]
It would be great if I can use any script (apple, shell) from context menu when I put them in some predefined folder, for example ~/Findermenu.

Similar to this project (abandoned)

https://github.com/samiyuru/custom-finder-right-click-menu

**Comment by kotleni** [comment]
@khurshid-alam A little specific feature, maybe i will implement it in future. (or you can impl it by youself)

**Comment by khurshid-alam** [comment]
Thanks. I would love to see that happen.
